# Generated by Django 4.2.3 on 2023-08-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
