# Generated by Django 4.2.3 on 2023-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerapp', '0002_delete_applicant_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('programs', models.CharField(max_length=1000)),
                ('Salary_expected', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=10)),
                ('Job_role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('Job_type', models.CharField(max_length=20)),
            ],
        ),
    ]
